ajaxDjango/ajaxDjango/urls.py
from django.contrib import admin
from django.urls import path

# from ajaxApp.views import(indexView, postFriend, checkNickName)
from ajaxApp.views import(FriendView,  checkNickName, CrawlView)

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', indexView),
    # path('post/ajax/friends', postFriend, name='post_friend'),
    path('get/ajax/validate/nickname', checkNickName, name='validate_nickname'),
    path('', FriendView.as_view(), name="friend_url"),
    path('crawl', CrawlView.as_view(), name="crawl_url")
]

ajaxDjango/ajaxApp/models.py
from django.db import models

# Create your models here.
class Friend(models.Model):
	nick_name = models.CharField(max_length = 100, unique = True)
	first_name = models.CharField(max_length = 100)
	last_name = models.CharField(max_length = 100)
	likes = models.CharField(max_length = 250)
	dob = models.DateField(auto_now = False, auto_now_add = False)
	lives_in = models.CharField(max_length = 150, null = True, blank = True)

	def __str__(self):
		return self.nick_name

class Crawl(models.Model):
	web_site = models.CharField(max_length=500, unique = True)
	block = models.CharField(max_length = 250)

	def __str__(self):
		return self.web_site

ajaxDjango/ajaxApp/forms.py
from .models import Friend
from django import forms
import datetime

from .models import Crawl

class FriendForm(forms.ModelForm):
	dob = forms.DateField(
			label = 'What is your birth date?',
			widget = forms.SelectDateWidget(years = range(1980, datetime.date.today().year - 5))
		)

	def __init__(self, *args, **kwargs):
		super(FriendForm, self).__init__(*args, **kwargs)

		for name in self.fields.keys():
			self.fields[name].widget.attrs.update({
				'class': 'form-controls',
				})

	class Meta:
		model = Friend
		fields = ("__all__")

class CrawlForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(CrawlForm, self).__init__(*args, **kwargs)

		for name in self.fields.keys():
			self.fields[name].widget.attrs.update({
				'class': 'form-controls',
				})
	class Meta:
		model = Crawl
		fields = ("__all__")

ajaxDjango/ajaxApp/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.core import serializers
from .forms import FriendForm
from .forms import CrawlForm
from .models import Friend
from .models import Crawl
from pprint import pprint
# Create your views here.

def indexView(request):
	form = FriendForm()
	friends = Friend.objects.all()
	return render(request, "index.html", {
		'form': form,
		'friends': friends
		})

def postFriend(request):
	#request should be ajax and method should be POST.
	if request.is_ajax and request.method == 'POST':
		form = FriendForm(request.POST)
		#save the data and after fetch the object in instance
		if form.is_valid():
			instance = form.save()
			ser_instance = serializers.serialize('json', [instance, ])
			#send to clint side
			return JsonResponse({'instance': ser_instance}, status=200)
		else:
			return JsonResponse({'error': form.errors}, status=400)	

	return JsonResponse({'error':''}, status=400)

def checkNickName(request):
	if request.is_ajax and request.method == 'GET':
		nick_name = request.GET.get('nick_name', None)
		if Friend.objects.filter(nick_name = nick_name).exists():
			return JsonResponse({"valid": False}, status = 200)
		else:
			return JsonResponse({"valid": True}, status = 200)

	return JsonResponse({}, status = 400)



from django.views import View

class FriendView(View):
	form_class = FriendForm
	template_name = "index.html"

	def get(self, *args, **kwargs):
		form = self.form_class()
		friends = Friend.objects.all()
		return render(self.request, self.template_name, 
			{"form": form, "friends": friends})

	def post(self, *args, **kwargs):
		if self.request.is_ajax and self.request.method == "POST":
			form = self.form_class(self.request.POST)

			if form.is_valid():
				instance = form.save()
				ser_instance = serializers.serialize('json', [ instance, ])

				# send to client side.
				return JsonResponse({"instance": ser_instance}, status=200)
			else:
				return JsonResponse({"error": form.errors}, status=400)

		return JsonResponse({"error": ""}, status=400)

class CrawlView(View):
	form_class = CrawlForm
	template_name = "craw.html"

	def get(self, *args, **kwargs):
		form = self.form_class()
		crawl = Crawl.objects.all()
		return render(self.request, self.template_name, {
				"form": form, "crawl": crawl
			})
		
	def post(self, *args, **kwargs):
		if self.request.is_ajax and self.request.method == "POST":
			# print ('hahah')

			form = self.form_class(self.request.POST)
			if form.is_valid():
				instance = form.save()
				ser_instance = serializers.serialize('json', [instance, ])
				return JsonResponse({"instance": ser_instance}, status = 200)
			else:
				return JsonResponse({"error": form.errors}, status=400)

		return JsonResponse({"error": ""}, status=400)

ajaxDjango/ajaxApp/templates/craw.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
	<form id="js-crawl-form">
		{% csrf_token %}
		{% for field in form %}
		<div class="form-group col-4">
			<label class="col-12">{{field.label }} </label>
			{{ field }}
		</div>
		{% endfor %}
		<input type="submit" class="btn btn-primary" value="Crawl Data" />
	</form>
</div>
<hr />
<div class="container-fluid">
	<table class="table table-striped table-sm" id="crawl_request">
		<thead>
			<tr>
				<th>Website</th>
                <th>Block</th>
			</tr>
		</thead>
		<tbody>
			{% for item in crawl %}
			<tr>
				<td>{{item.web_site}}</td>
	            <td>{{item.block}}</td>
       		 </tr>
       		 {% endfor %}
		</tbody>
	</table>
</div>
{% endblock content %}

{% block javascript %}
<script>
	$('#js-crawl-form').submit(function(e){
		e.preventDefault();
		var serializedData = $(this).serialize();
		$.ajax({
			type: 'POST',
			url: "{% url 'crawl_url' %}",
			data: serializedData,
			success: function (response){
				//on successfull creating object
				console.log(response);
				//1. clear the form.
				$("#js-crawl-form").trigger('reset');

				//display the newly friend to table.
				var instance = JSON.parse(response['instance']);
				var fields = instance[0]['fields'];

				$('#crawl_request tbody').prepend(
					`<tr>
						<td>${fields["web_site"]||""}</td>
	                    <td>${fields["block"]||""}</td>
					</tr>
					`
				)
			},
			error: function (response){
				//alert the error if any error occured
				alert(response['responseJSON']['error']);
			}
		})
	})

	// $('#id_nick_name').focusout(function(e){
	// 	e.preventDefault();
	// 	var nick_name = $(this).val();

	// 	$.ajax({
	// 		type: 'GET',
	// 		url: "{% url 'validate_nickname' %}",
	// 		data: {'nick_name': nick_name},
	// 		success: function(reponse){
	// 			if(!reponse['valid']){
	// 				alert("You cannot create a friend with the same nick name");
	// 				var nickName = $('#id_nick_name');
	// 				nickName.val("")
	// 				nickName.focus()
	// 			}
	// 		},
	// 		error: function (response){
	// 			console.log(response)
	// 		}
	// 	})
	// });
</script>
{% endblock javascript %}

ajaxDjango/ajaxApp/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
	<form id="friend-form">
		{% csrf_token %}
		{% for field in form %}
		<div class="form-group col-4">
			<label class="col-12">{{field.label }} </label>
			{{ field }}
		</div>
		{% endfor %}
		<input type="submit" class="btn btn-primary" value="Create Friend" />
	</form>
</div>
<hr />
<div class="container-fluid">
	<table class="table table-striped table-sm" id="my_friends">
		<thead>
			<tr>
				<th>Nick name</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Likes</th>
                <th>DOB</th>
                <th>lives in</th>
			</tr>
		</thead>
		<tbody>
			{% for friend in friends %}
			<tr>
				<td>{{friend.nick_name}}</td>
	            <td>{{friend.first_name}}</td>
	            <td>{{friend.last_name}}</td>
	            <td>{{friend.likes}}</td>
	            <td>{{friend.dob | date:"Y-m-d"}}</td>
	            <td>{{friend.lives_in}}</td>
       		 </tr>
       		 {% endfor %}
		</tbody>
	</table>
</div>
{% endblock content %}

{% block javascript %}
<script>
	$('#friend-form').submit(function(e){
		e.preventDefault();
		var serializedData = $(this).serialize();
		$.ajax({
			type: 'POST',
			url: "{% url 'friend_url' %}",
			data: serializedData,
			success: function (response){
				//on successfull creating object
				// console.log(response);
				//1. clear the form.
				$("#friend-form").trigger('reset');
				$("#id_nick_name").focus();

				//display the newly friend to table.
				var instance = JSON.parse(response['instance']);
				var fields = instance[0]['fields'];

				$('#my_friends tbody').prepend(
					`<tr>
						<td>${fields["nick_name"]||""}</td>
	                    <td>${fields["first_name"]||""}</td>
	                    <td>${fields["last_name"]||""}</td>
	                    <td>${fields["likes"]||""}</td>
	                    <td>${fields["dob"]||""}</td>
	                    <td>${fields["lives_in"]||""}</td>
					</tr>
					`
				)
			},
			error: function (response){
				//alert the error if any error occured
				alert(response['responseJSON']['error']);
			}
		})
	})

	$('#id_nick_name').focusout(function(e){
		e.preventDefault();
		var nick_name = $(this).val();

		$.ajax({
			type: 'GET',
			url: "{% url 'validate_nickname' %}",
			data: {'nick_name': nick_name},
			success: function(reponse){
				if(!reponse['valid']){
					alert("You cannot create a friend with the same nick name");
					var nickName = $('#id_nick_name');
					nickName.val("")
					nickName.focus()
				}
			},
			error: function (response){
				console.log(response)
			}
		})
	});
</script>
{% endblock javascript %}

ajaxDjango/ajaxDjango/templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="description" content="IE=chrome">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Ajax Django</title>
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
         {% block style %}
    	 {% endblock style %}
        <link rel="author" href="humans.txt">
    </head>
    <body>
        {% block content %}
        {% endblock content %}

         <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	    {% block javascript %}
    	{% endblock javascript %}
    
    </body>
</html>